### PR TITLE
Make it compatible lodash@4

### PR DESCRIPTION
**Pull request by JSteunou**
Hi @alexbeletsky!

long time no see ;) I'm using lodash instead of underscore, and since lodash@4 (and future underscore) there are some breaking changes.

This PR fixes this.

### CODE REVIEW

**Comment by JSteunou** [comment]
still around @alexbeletsky ?

**Comment by JSteunou** [comment]
@alexbeletsky could you please take a look at this ?

**Comment by alexbeletsky** [comment]
@JSteunou thanks!

**Comment by JSteunou** [comment]
no problem, glad to see you are still a little active :)

Do you think you could make a new release with those changes?

**Comment by alexbeletsky** [comment]
sorry, I'm indeed not active with this project (as well as my other open source :)

I was about to release it yesterday, but I have one concern. [Here](https://github.com/alexbeletsky/backbone-computedfields/blob/master/lib/amd/backbone.computedfields.js#L9) I still use underscore as a dependency. Do you think, with your changes would it work correctly?

**Comment by JSteunou** [comment]
Yep, this is not an issue. My PR was just to update your use of underscore each, reduce, ... so backbone.computedFields users can alias underscore with latest lodash (in webpack config, requirejs, etc) to force the use of lodash instead of underscore everywhere

**Pull request merged**
